### ISSUE TITLE
A simple example of using the library

### ISSUE THREAD

**Issue by ali-alizadeh** [dart-league/Font-Awesome#2]
Hi everyone.
I have installed this library on my flutter web project, but I really have no idea how to use it.
I thought I should import the library in my project like every other library, but I just couldn't find a dart file in order to import and make use of the library.
Please add a simple example of the way we should use the library in flutter web projects.
Thank you.

**Comment by zubairehman** [comment]
I am stuck as well :(

**Comment by luisvt** [comment]
the only thing that could be imported is the generated `css` files or the `scss` sources

**Comment by ali-alizadeh** [comment]
@luisvt Thanks for your response. Could u give me a simple example? How can I use the icons after importing the `css` files or the `scss` sources?

**Comment by luisvt** [comment]
Please check this:
https://github.com/dart-league/Font-Awesome/tree/master/examples
